name: Laravel Tests with Redis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DB_CONNECTION: mysql
  DB_DATABASE: laravel_test
  DB_USERNAME: root
  DB_PASSWORD: secret
  CACHE_DRIVER: redis
  REDIS_HOST: 127.0.0.1
  REDIS_PORT: 6379

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, ctype, fileinfo, dom, curl, pdo, mysql, bcmath, gd, imagick, redis
          coverage: pcov
          ini-values: memory_limit=2G

      - name: Validate composer.json
        run: composer validate --strict

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Prepare environment
        run: |
          cp .env.example .env.testing
          echo "APP_ENV=testing" >> .env.testing
          echo "APP_KEY=base64:$(openssl rand -base64 32)" >> .env.testing
          echo "CACHE_DRIVER=redis" >> .env.testing
          echo "REDIS_HOST=127.0.0.1" >> .env.testing
          echo "REDIS_PORT=6379" >> .env.testing
          echo "SESSION_DRIVER=redis" >> .env.testing
          echo "QUEUE_CONNECTION=redis" >> .env.testing

      - name: Generate app key
        run: php artisan key:generate --env=testing

      - name: Clear and cache config
        run: |
          php artisan config:clear --env=testing
          php artisan config:cache --env=testing

      - name: Run migrations
        run: php artisan migrate:fresh --env=testing --force

      - name: Clear Redis before tests
        run: |
          php artisan cache:clear --env=testing
          redis-cli -h 127.0.0.1 FLUSHALL

      - name: Run tests
        run: php artisan test --env=testing
